luckybocky/luckybocky

back/luckybocky/src/main/java/com/project/luckybocky/article/entity/Article.java, back/luckybocky/src/main/java/com/project/luckybocky/common/BaseEntity.java, back/luckybocky/src/main/java/com/project/luckybocky/common/CommonResponseDto.java, back/luckybocky/src/main/java/com/project/luckybocky/fortune/entity/Fortune.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/controller/PocketController.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/dto/NewPocketDto.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/entity/Pocket.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/repository/PocketRepository.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/service/PocketService.java, back/luckybocky/src/main/java/com/project/luckybocky/user/entity/User.java, back/luckybocky/src/main/resources/firebase/test.json
User, Pocket, Article, Fortune
=> Feat: Add Entity

back/luckybocky/src/main/java/com/project/luckybocky/common/RestTemplateConfig.java, back/luckybocky/src/main/java/com/project/luckybocky/login/contorller/LoginController.java, back/luckybocky/src/main/java/com/project/luckybocky/login/dto/LoginDto.java, back/luckybocky/src/main/java/com/project/luckybocky/login/service/LoginService.java, back/luckybocky/src/main/java/com/project/luckybocky/user/dto/UserDto.java, back/luckybocky/src/main/java/com/project/luckybocky/user/entity/User.java, back/luckybocky/src/main/java/com/project/luckybocky/user/repository/UserRepository.java
파일 수정한 것: User Entity
변경하기로 합의한 것: Spring Data JPA
=> Feat: back login

back/luckybocky/src/main/java/com/project/luckybocky/article/entity/Article.java, back/luckybocky/src/main/java/com/project/luckybocky/common/Message.java, back/luckybocky/src/main/java/com/project/luckybocky/login/contorller/LoginController.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/entity/Pocket.java
response 일관성있게 반환하고자 Message 클래스 추가하고 반환형태 변경했습니다.
=> Woojae back/login

back/luckybocky/src/main/java/com/project/luckybocky/common/BaseEntity.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/controller/FeedbackController.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/dto/FeedbackDto.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/dto/FeedbackReqDto.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/dto/FeedbackResDto.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/entity/Feedback.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/repository/FeedbackRepository.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/service/FeedbackService.java
1. 나중에 피드백 조회 쉽게 하려고 조회 api 따로 만들었습니다.
2. Base Entity Getter 추가했습니다. -> 조회했을 때 시간도 확인하기 위함 -> DTO 초기화 과정에서 공통속성 접근하려면 필요했음
3. 추후 예외 처리 확실하게 하겠음 -> 지금은 이분법적으로 반환하는 형태임 -> 되거나 안 되거나
=> Woojae back/feat/feedback

back/luckybocky/src/main/java/com/project/luckybocky/user/controller/SettingController.java, back/luckybocky/src/main/java/com/project/luckybocky/user/dto/SettingDto.java, back/luckybocky/src/main/java/com/project/luckybocky/user/entity/User.java, back/luckybocky/src/main/java/com/project/luckybocky/user/service/UserSettingService.java, back/luckybocky/src/main/java/com/project/luckybocky/user/service/UserSettingServiceImpl.java
=> add method updateUserSetting(userNickname, alarmStatus, fortuneVisibility)

back/luckybocky/src/main/java/com/project/luckybocky/common/WebMvcConfig.java, back/luckybocky/src/main/java/com/project/luckybocky/login/dto/LoginDto.java, back/luckybocky/src/main/java/com/project/luckybocky/login/service/LoginService.java, back/luckybocky/src/main/java/com/project/luckybocky/user/entity/User.java
=> Feat : cors,fix

back/luckybocky/.gitignore, back/luckybocky/src/main/java/com/project/luckybocky/feedback/dto/FeedbackDto.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/service/FeedbackService.java, back/luckybocky/src/main/java/com/project/luckybocky/report/controller/ReportController.java, back/luckybocky/src/main/java/com/project/luckybocky/report/dto/ReportDto.java, back/luckybocky/src/main/java/com/project/luckybocky/report/dto/ReportReqDto.java, back/luckybocky/src/main/java/com/project/luckybocky/report/dto/ReportResDto.java, back/luckybocky/src/main/java/com/project/luckybocky/report/repository/ReportRepository.java, back/luckybocky/src/main/java/com/project/luckybocky/report/service/ReportService.java
FeedbackDto에 몇 번째 피드백인지 확인할 수 있도록 feedbackSeq 변수 추가
=> Refactor: add feedbackSeq variable

back/luckybocky/Dockerfile, back/luckybocky/src/main/java/com/project/luckybocky/common/WebMvcConfig.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/controller/PocketController.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/entity/Pocket.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/service/PocketService.java
- 복주머니 생성 쪽 살짝 수정
- 복주머니 테이블 유저 유니크 설정
- cors 설정 front uri properties에 저장
- 도커 파일 추가
=> Refactor : pocket

front/package-lock.json, front/src/api/CommentApi.js, front/src/api/ReportApi.js, front/src/components/Article.js, front/src/components/Comment.js, front/src/components/Menu.js, front/src/pages/MainPage.js
근데 컴포넌트로 빼서 하려고 노력하니까 구성이 이상해서 허락해주신다면 Article.js에 바로 넣고 싶음
=> Feat: 답장하기 api, 프론트

back/luckybocky/src/main/java/com/project/luckybocky/article/dto/ArticleResponseDto.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/controller/PocketController.java
1. 기능적인 코드를 따로 추가한 것은 아님
2. 프론트 기능 구현 과정에서 에러 발생하는 코드 수정
article.getUser().getUserKey();
위의 경우 게스트 상태일경우, getUser() 자체가 null이라 getUserKey() 호출 불가
pocketDto.setPocketSeq(findPocket.getPocketSeq());
복 다는 과정에서 위 코드 누락으로 모든 복주머니 Seq가 0으로 초기화되는 문제 발생
=> Feat: 복 달기 프론트엔드 기능 구현 과정에서 필요한 코드 추가

back/luckybocky/src/main/java/com/project/luckybocky/kakao/contorller/KakaoController.java, back/luckybocky/src/main/java/com/project/luckybocky/kakao/dto/KakaoLoginDto.java, back/luckybocky/src/main/java/com/project/luckybocky/kakao/service/KakaoService.java
* 특이사항
* 로그아웃 기능이 추가됨에 따라 패키지명을 login에서 kakao로 변경
=> Feat: logout

back/luckybocky/src/test/java/com/project/luckybocky/LuckybockyApplicationTests.java
=> Fix : test_build_error

back/luckybocky/src/main/java/com/project/luckybocky/article/exception/ArticleNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticlePushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/common/GlobalExceptionHandler.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/exception/PocketNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/service/PocketPushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/push/controller/PushController.java, back/luckybocky/src/main/java/com/project/luckybocky/push/service/PushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/user/controller/FireBaseController.java, back/luckybocky/src/main/java/com/project/luckybocky/user/controller/SettingController.java, back/luckybocky/src/main/java/com/project/luckybocky/user/exception/UserNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/user/service/UserSettingService.java, back/luckybocky/src/main/java/com/project/luckybocky/user/service/UserSettingServiceImpl.java
설정변경,  내가 보낸 복보기, 내 정보 조회, 파이어베이스 키 업데이트, 복 푸시알림,  리복 푸시알림 예외처리 했습니다.
커스텀 예외 만들어서 각 도메인에 넣어왔습니다. 예외 핸들링은 GlobalException에 추가했습니다.
=> Feat : 마이페이지, 푸시 예외 처리

back/luckybocky/build.gradle, back/luckybocky/src/main/java/com/project/luckybocky/common/SwaggerConfig.java, back/luckybocky/src/main/java/com/project/luckybocky/exam/ExamController.java, back/luckybocky/src/main/java/com/project/luckybocky/exam/ExamDataResponseDto.java, back/luckybocky/src/main/java/com/project/luckybocky/exam/ExamDto.java, back/luckybocky/src/main/java/com/project/luckybocky/exam/ExamResponseDto.java, back/luckybocky/src/main/java/com/project/luckybocky/exam/ExamService.java, back/luckybocky/src/main/java/com/project/luckybocky/exam/exception/CustomException.java, back/luckybocky/src/main/java/com/project/luckybocky/exam/exception/ExamException.java
- 스웨거 기본 설정(배포 환경에서는 나중에 빌드 될 때 확인)
- 스웨거, response, exception 관련 예시 추가
=> Feat : swagger

back/luckybocky/src/main/java/com/project/luckybocky/article/controller/MyArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/push/controller/PushController.java, back/luckybocky/src/main/java/com/project/luckybocky/user/controller/FireBaseController.java, back/luckybocky/src/main/java/com/project/luckybocky/user/controller/SettingController.java
=> Feat : description 추가

back/luckybocky/src/main/java/com/project/luckybocky/common/SwaggerConfig.java
- 배포 환경에서의 swagger cors 해결을 위해 설정 추가
=> Feat : swagger_https

back/luckybocky/src/main/java/com/project/luckybocky/auth/contorller/AuthController.java, back/luckybocky/src/main/java/com/project/luckybocky/auth/exception/LoginFailedException.java, back/luckybocky/src/main/java/com/project/luckybocky/common/NicknameNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/common/SessionNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/controller/FeedbackController.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/exception/FeedbackNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/exception/FeedbackSaveException.java, back/luckybocky/src/main/java/com/project/luckybocky/report/controller/ReportController.java, back/luckybocky/src/main/java/com/project/luckybocky/report/exception/ReportNotFoundException.java
* 진행 상황
* 담당 부분 스웨거 추가 및 확인 완료
* 특이 사항
* 로그인 부분의 경우 OAuth 처리 과정 특성상 테스트 불가
=> Refact: swagger 추가

back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticlePushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/common/FCMInitializer.java, back/luckybocky/src/main/java/com/project/luckybocky/push/controller/PushController.java, back/luckybocky/src/main/java/com/project/luckybocky/push/service/PushServiceImpl.java
백엔드 푸시 알림 수정
1. 닉네임으로 푸시전송
2. 리복할때 복 주인으로 푸시
3. 비회원과 파이어베이스키가 없을때 예외처리
=> Feat : 백엔드 push 오류 수정

front/src/api/FireBaseApi.js, front/src/index.js
서비스워커 등록시, IOS환경과 사파리에서 에러가 발생하는것으로 추정.
서비스워커 등록전에 IOS환경을 판별하는 코드 추가
=> Feat : 푸시알림 프론트 IOS 예외 시도

front/src/api/FireBaseApi.js
=> Feat : 푸시알림 프론트 IOS 예외 시도2

front/src/api/FireBaseApi.js, front/src/index.js
=> Feat : 푸시알림 프론트 IOS 예외 시도3

front/src/index.js
=> Feat : 푸시알림 프론트 IOS 예외 시도4

back/luckybocky/src/main/java/com/project/luckybocky/article/controller/ArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/dto/ArticleResponseDto.java, back/luckybocky/src/main/java/com/project/luckybocky/article/dto/ArticleSummaryDto.java, back/luckybocky/src/main/java/com/project/luckybocky/article/entity/Article.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticleService.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/controller/PocketController.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/dto/PocketDto.java
- 복주머니 불러오기 로직 수정 (게시글 전체 내용이 아닌 요약 내용으로 리스트 불러옴)
- 복주머니 비밀글 로직 상세로 이동
- entity boolean으로 통일
=> Refactor : visibility

front/src/api/FireBaseApi.js
=> Feat : 푸시알림 프론트 IOS 예외 시도5

front/package-lock.json, front/package.json, front/src/api/FireBaseApi.js, front/src/index.js
IOS 카카오톡 인앱뷰는 WKWebView를 기반으로 하며, Safari 브라우저와 동일한 렌더링 엔진(WebKit)을 사용하기 때문에 최신 core-js 및 polyfill 라이브러리를 추가해 호환성을 확보
=> Feat : 푸시알림 프론트 IOS 예외 시도6

front/src/index.js
=> Feat : 푸시알림 프론트 IOS 예외 시도7

front/src/router.js
브라우저라우터가 IOS에서 정상적으로 동작하지 않을수 가 있다고 해서, 해시 라우터로 변경
=> Feat : 푸시알림 프론트 IOS 예외 시도8

front/src/index.js, front/src/router.js
=> Feat : 푸시알림 프론트 IOS 예외 시도9

back/luckybocky/src/main/java/com/project/luckybocky/common/SwaggerConfig.java
=> Refactor : swagger_uri

front/package-lock.json, front/package.json
=> Feat : 푸시알림 프론트 IOS 예외 시도11

front/src/api/FireBaseApi.js, front/src/components/firebase-config.js, front/src/index.js, front/src/pages/LoginPage.js
=> Feat : 프론트 로그추가

back/luckybocky/build.gradle, back/luckybocky/src/main/java/com/project/luckybocky/push/controller/PushController.java
=> Changhee push

front/src/components/firebase-config.js, front/src/index.js
=> Feat : 프론트 예외처리

front/src/components/firebase-config.js
=> Feat : 파이어베이스 초기화 예외처리

front/src/pages/LoginPage.js, front/src/pages/MainPage.js
=> Feat : 서비스워커, 파이어베이스 함수 변경

back/luckybocky/src/main/java/com/project/luckybocky/push/controller/PushController.java
=> Feat : 백엔드 로그 추가

back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticleService.java
- 비밀글 UI를 위해 글의 설정과 관계없이 이용자에게 보여지냐 안 보여지냐로 visibility 설정
=> Refactor : visibility_setting

back/luckybocky/src/main/java/com/project/luckybocky/article/controller/MyArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/MyArticleServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/common/GlobalExceptionHandler.java, back/luckybocky/src/main/java/com/project/luckybocky/push/controller/PushController.java, back/luckybocky/src/main/java/com/project/luckybocky/user/controller/FireBaseController.java, back/luckybocky/src/main/java/com/project/luckybocky/user/controller/SettingController.java
=> Feat : swagger 수정

back/luckybocky/src/main/java/com/project/luckybocky/article/controller/ArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/exception/ArticleNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/article/exception/CommentConflictException.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticlePushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticleService.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/MyArticleServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/common/CustomException.java, back/luckybocky/src/main/java/com/project/luckybocky/common/GlobalExceptionHandler.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/service/FeedbackService.java, back/luckybocky/src/main/java/com/project/luckybocky/fortune/exception/FortuneNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/exception/PocketNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/service/PocketPushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/service/PocketService.java, back/luckybocky/src/main/java/com/project/luckybocky/push/service/PushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/report/service/ReportService.java, back/luckybocky/src/main/java/com/project/luckybocky/user/exception/ForbiddenUserException.java, back/luckybocky/src/main/java/com/project/luckybocky/user/exception/UserNotFoundException.java, back/luckybocky/src/main/java/com/project/luckybocky/user/service/UserSettingServiceImpl.java
모든 예외는 CustomException을 상속받아서 구현.
상태코드와 메시지는 각 예외의 static 필드변수로 작성하고 상위 클래스로 전달하기 때문에, 예외를 호출할때 인자가 필요없음.
=> Feat : CustomException 추가

back/luckybocky/src/main/java/com/project/luckybocky/article/controller/ArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/controller/CommentController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/controller/MyArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/dto/CommentDto.java, back/luckybocky/src/main/java/com/project/luckybocky/article/dto/WriteArticleDto.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticlePushService.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticlePushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/service/PocketPushService.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/service/PocketPushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/push/controller/PushController.java, back/luckybocky/src/main/java/com/project/luckybocky/push/dto/PushDto.java, back/luckybocky/src/main/java/com/project/luckybocky/push/service/PushService.java, back/luckybocky/src/main/java/com/project/luckybocky/push/service/PushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/user/controller/SettingController.java, back/luckybocky/src/main/java/com/project/luckybocky/user/service/UserSettingServiceImpl.java
1. 파이어베이스 키 업데이트, 유저 정보 변경 컨트롤러 통합
2. 푸시알림기능을 복, 리복할때 수행하도록 통합
3. PushService 코드 리팩토링
=> Feat : 푸시 알림 통합, 유저 세팅 기능 통합

front/src/pages/AccountPage.js
1. IOS환경에서 Notification오류가 발생한거 해결 시도
=> Feat : nofitication 오류 수정

back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticlePushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/common/GlobalExceptionHandler.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/service/PocketPushServiceImpl.java
=> Feat : 파이어베이스 응답코드변경, 로그 추가

back/luckybocky/src/main/java/com/project/luckybocky/article/controller/ArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/controller/PocketController.java
ArticleController, PocketController에 정보성 로그 추가
=> Refactor: Add log - ArticleController, PocketController

back/luckybocky/src/main/java/com/project/luckybocky/article/controller/ArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/controller/CommentController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticleService.java, back/luckybocky/src/main/java/com/project/luckybocky/push/dto/PushDto.java, back/luckybocky/src/main/java/com/project/luckybocky/push/enums/PushMessage.java, back/luckybocky/src/main/java/com/project/luckybocky/push/service/PushService.java, back/luckybocky/src/main/java/com/project/luckybocky/push/service/PushServiceImpl.java
- ArticleService에서만 pushService에 의존하도록 변경
- 서비스워커에서 등록된 백그라운드 알림을 사용하기 위해 notification 제거
- 알림의 장애가 알림을 사용하는 서비스의 장애로 전파되지 않도록 변경
추가로 아마 충돌날 거 같은데 해결하고 머지할게유
=> Refactor : push

back/luckybocky/build.gradle, back/luckybocky/src/main/java/com/project/luckybocky/article/controller/ArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/controller/CommentController.java, back/luckybocky/src/main/java/com/project/luckybocky/auth/contorller/AuthController.java, back/luckybocky/src/main/java/com/project/luckybocky/feedback/controller/FeedbackController.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/controller/PocketController.java, back/luckybocky/src/main/java/com/project/luckybocky/push/service/PushServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/qna/controller/QnaController.java, back/luckybocky/src/main/java/com/project/luckybocky/report/controller/ReportController.java, back/luckybocky/src/main/java/com/project/luckybocky/user/controller/SettingController.java
- C,U,D에 대하여 1초에 1요청만 가능하도록 설정
충돌뜨면 어노테이션 쪽만 신경써서 머지 부탁합니다
=> Feat : 중복 요청 방지

back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticleService.java
=> Fix : 비밀글 로직

back/luckybocky/src/main/java/com/project/luckybocky/user/controller/SettingController.java
=> Refactor : userUpdateLimit

back/luckybocky/src/main/java/com/project/luckybocky/common/BaseEntity.java, back/luckybocky/src/main/java/com/project/luckybocky/common/GlobalExceptionHandler.java, back/luckybocky/src/main/java/com/project/luckybocky/qna/controller/QnaController.java, back/luckybocky/src/main/java/com/project/luckybocky/qna/dto/QnaDto.java, back/luckybocky/src/main/java/com/project/luckybocky/qna/entity/Qna.java, back/luckybocky/src/main/java/com/project/luckybocky/qna/exception/QnaDeleteException.java, back/luckybocky/src/main/java/com/project/luckybocky/qna/exception/QnaUpdateException.java, back/luckybocky/src/main/java/com/project/luckybocky/qna/service/QnaService.java
* 진행 사항
* QnA 수정/삭제
* QnA 조회 로직 에러 수정
=> Feat: QnA 수정/삭제

front/src/api/QnaService.ts, front/src/pages/QnaBoardPage.js, front/src/pages/QnaDetailPage.js
* 진행 사항
* 질문 수정 및 삭제
* 질문 삭제 모달
* 답변달렸을 때 질문 수정 불가
* 삭제 자체는 가능
* 필터링 상태관리 에러 수정
* 특이 사항
* 수정이나 답변달았을 때 화면에 즉시 랜더링으로 변경이 반영되는 '척'
* 새로고침하면 변경 전으로 랜더링 -> 변경이 안 됐다는 소리가 아님
* 해결하려고 노력했으나 시간 관계상 수행하지 못했음..
=> Woojae front/feat/qna

back/luckybocky/src/main/java/com/project/luckybocky/qna/controller/QnaController.java, back/luckybocky/src/main/java/com/project/luckybocky/qna/dto/QnaDto.java, back/luckybocky/src/main/java/com/project/luckybocky/qna/service/QnaService.java
* 진행 사항
* 데이터 요청할 때 사용자 권한에 따라 데이터 은닉 적용
* 특이 사항
* 현재는 임시 코드로, 추후 구조 변경할 것
=> Refact: 데이터 은닉 필터링

front/src/components/Article.js, front/src/components/Menu.js, front/src/pages/QnaBoardPage.js
- flag 상태가 false일 때 fetch가 되지 않는 문제 fix
- flag의 default 값을 세션에서 바로 받아오게 함으로써 렌더링이 중복되는 문제 fix
=> Fix : flag_fetch

back/luckybocky/src/main/java/com/project/luckybocky/article/entity/Article.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/entity/ShareArticle.java, back/luckybocky/src/main/java/com/project/luckybocky/user/entity/User.java
=> Back share article

back/luckybocky/src/main/java/com/project/luckybocky/common/GlobalExceptionHandler.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/controller/ShareArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/dto/ShareArticleDto.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/dto/ShareArticleSeqDto.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/dto/WriteShareArticleDto.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/entity/ShareArticle.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/exception/ShareArticleException.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/repository/ShareArticleRepository.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/sevice/ShareArticleService.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/sevice/ShareArticleServiceImpl.java, back/luckybocky/src/main/java/com/project/luckybocky/user/entity/User.java, back/luckybocky/src/main/java/com/project/luckybocky/user/repository/UserSettingRepository.java
=> Feat : 공유게시글 생성 작성

back/luckybocky/src/main/java/com/project/luckybocky/qna/dto/QnaDto.java
* 진행 사항
* 질문이 등록되지마자 답변 완료 처리되는 문제 수정
* 질문의 내용으로 답변이 자동으로 달리는 문제 수정
* 이유
* dto 초기화 잘못함
=> Fix: 답변이 달리지 않았는데도 답변 완료 처리되는 에러 수정

back/luckybocky/src/main/java/com/project/luckybocky/article/entity/Article.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/controller/ShareArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/sevice/ShareArticleService.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/sevice/ShareArticleServiceImpl.java
공유게시글 조회 작성
1. 회원일 경우 : 해당 공유게시글이 본인의 게시글로 복제되고, 자신에게 추가된다.  자기가 만든 공유게시글이거나, 이미 가지고 있는 경우에는 아무일도 일어나지않는다.
2. 비회원일떄 : 로그인 창으로 고고
=> Feat : 공유게시글 조회 작성

back/luckybocky/src/main/java/com/project/luckybocky/article/dto/ArticleResponseDto.java, back/luckybocky/src/main/java/com/project/luckybocky/article/entity/Article.java
- article 상세 불러오기에 작성자의 복주머니 주소 추가
=> Feat : pocketAddress

back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/dto/ShareArticleDto.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/entity/ShareArticle.java
=> Feat : share_usernickname

back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/dto/ShareArticleDto.java, back/luckybocky/src/main/java/com/project/luckybocky/sharearticle/entity/ShareArticle.java
ShareArticleDto에  공유게시글을 만든 유저의 복주머니 주소 추가 
"pocketAddress": String
=> Feat : ShareArticleDto애 복주머니 주소 추가

back/luckybocky/src/main/java/com/project/luckybocky/article/service/MyArticleServiceImpl.java
- 공유된 글로 저장된 글은 내가 쓴 글 목록에 안 뜨게 변경
=> Fix : myArticle

front/src/pages/shareArticlePage.tsx
=> Refactor : sharePage_font_color

back/luckybocky/src/main/java/com/project/luckybocky/article/dto/MyArticleDto.java, back/luckybocky/src/main/java/com/project/luckybocky/article/entity/Article.java
- myArticle api PocketAddress 추가
=> Feat : myArticle_pocketAddress

back/luckybocky/src/main/java/com/project/luckybocky/article/controller/ArticleController.java, back/luckybocky/src/main/java/com/project/luckybocky/article/service/ArticleService.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/controller/PocketController.java, back/luckybocky/src/main/java/com/project/luckybocky/pocket/service/PocketService.java
1. Log 생성 위치 변경
- Controller to Service
2. Log 내용 "유저 {}, 대상 {}"으로 통일
3. 일반 조회 시 로그 삭제
Refactor: Add get userSeq by Session
세션에서 userSeq 가져와서 key로 사용하는 로직 추가.
아직 세션에 값을 담아놓지 않아서 주석처리해둠.
+) 저희 이제 비회원은 게시글 작성 아예 못하는거 맞는지..? 관련해서 코드 약간만 수정하고 싶은데 기능이 자꾸 바꼈어서 확인차 질문합니다...
=> Refactor: Edit Log

back/luckybocky/src/main/java/com/project/luckybocky/user/service/UserSettingServiceImpl.java
- 비회원 더미 데이터로 인해 비회원도 회원 정보를 로그인으로 전달하는 문제 수정
=> Fix : userCheck
